apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autoally-gateway
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: autoally-gateway.fullstackjam.com
    http:
      paths:
      - path: /imadapter(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: autoally-imadapter
            port:
              number: 8000
