name: Deploy to Kubernetes

on:
  push:
    branches:
      - master # Adjust this to your main branch if it's not "master"

jobs:
  deploy_ingress_controller:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Kubernetes config
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $GITHUB_WORKSPACE/kubeconfig
        chmod 600 $GITHUB_WORKSPACE/kubeconfig  # Set kubeconfig file permissions

    - name: Check Cluster Availability
      continue-on-error: true
      run: |
        kubectl cluster-info --insecure-skip-tls-verify --kubeconfig $GITHUB_WORKSPACE/kubeconfig && echo "cluster_status=available" >> $GITHUB_ENV || echo "cluster_status=unavailable" >> $GITHUB_ENV

    - name: Add Helm repository for Nginx Ingress
      if: env.cluster_status == 'available'
      run: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

    - name: Update Helm repositories
      if: env.cluster_status == 'available'
      run: helm repo update

    - name: Install Nginx Ingress Controller
      if: env.cluster_status == 'available'
      run: helm upgrade --install nginx-ingress ingress-nginx/ingress-nginx --set controller.service.type=NodePort   --set controller.service.nodePorts.http=30489 --set controller.service.nodePorts.https=30903 --kubeconfig $GITHUB_WORKSPACE/kubeconfig

    - name: Deploy with Helm
      if: env.cluster_status == 'available'
      run: helm upgrade --install gateway-release helm/autoally-gateway --atomic --kubeconfig $GITHUB_WORKSPACE/kubeconfig
