name: Deploy to Kubernetes

on:
  push:
    branches:
      - master # Adjust this to your main branch if it's not "master"

jobs:
  deploy_ingress_controller:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Kubernetes config
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $GITHUB_WORKSPACE/kubeconfig

    - name: Add Helm repository for Nginx Ingress
      run: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

    - name: Update Helm repositories
      run: |
        helm repo update

    - name: Install Nginx Ingress Controller
      run: |
        helm upgrade --install nginx-ingress ingress-nginx/ingress-nginx --kubeconfig $GITHUB_WORKSPACE/kubeconfig

  
  deploy_to_kubernetes:
    needs: deploy_ingress_controller
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Kubernetes config
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $GITHUB_WORKSPACE/kubeconfig

    - name: Setup Helm
      uses: azure/setup-helm@v1
      with:
        version: '3.6.0' # Set your desired Helm version

    - name: Deploy with Helm
      run: |
        helm upgrade --install gateway-release helm/autoally-gateway --atomic --kubeconfig $GITHUB_WORKSPACE/kubeconfig
